## 1
Hello world:

```{r}
print('Hello world!')
```

```{r}
2+2
```

```{r}
cat('Hello world!')
```
```{r}
144**99
```
## 2
Переменные:

```{r}
a <- 9
b <- 10

a+b
a*b+3
a-b
a < b
a == b
b = a
b == a
```

# 3
Вещественные числа:
```{r}
0.2+0.1 == 0.3
all.equal(0.2+0.1, 0.3)
```

# 4
Условия:
```{r}
a = 1
b = 2

if (a < b) {
  print("True!")
} else {
  print("False!")
}
```

# 5
Циклы:
```{r}
c <- 5
while(c < 9) {
  c <- c + 1
}
```
```{r}
for (i in 1:5) {
  print(i)
}
```

# 6
Функции:
```{r}
max_of_two <- function(a, b) {
  if (a > b) {
    return(a)
  } else {
    return(b)
  }
}

print(max_of_two(3, 4))
print(max_of_two(10, 9))
print(max_of_two(max_of_two(1, 2), 3))
```

# 7
Стандартные функции:
```{r}
seq <- 3:15
mean(seq)
max(seq)
min(seq)
sum(seq)
```

# 8
Либы:
```{r}
d <- 1/3
e <- 1/5
d + e

library(MASS)
print(fractions(d+e))
```

# 9 
Векторы:
```{r}
x <- c(1, 2, 3, 5)
class(x)
y <- c("a", "b", "c")
class(y)
z <- c(1, "b", "c")
class(z)

u <- c(-1, 2, 3, 0)
i <- c(8, 4, 9, -6)

u * i
u + i
u[1]
u[1:3]
u[u>0]

l <- c(1000, 248, 29084, 238642, 483973, 9204)
max(l)
min(l)
mean(l)
median(l)

var(x)
sd(x)
```

# 10
Матрицы
```{r}
x <- c(1, 2, 3, 4, 5, 6)
m <- matrix(x, nrow = 2)
m
n <- matrix(x, ncol = 2)
n

a <- c(2390, 218973, 1893891, 12837)
b <- c(128937, 1238, 328791, 9483)
c <- c(3498, 2930, 29304, 1091)

cbind(a, b, c)
rbind(a, b, c)

m[2, 3]
m[1,]
m[, 2]

```

